# Generated by Django 4.2.9 on 2024-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=254)),
                ("password", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=254)),
                ("email", models.CharField(max_length=254)),
                ("mobile", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=254)),
                ("cfrm_password", models.CharField(max_length=254)),
            ],
        ),
    ]
