# Generated by Django 4.2.9 on 2024-11-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_alter_register_email_commandexecutinglog"),
    ]

    operations = [
        migrations.RemoveField(model_name="commandexecutinglog", name="user",),
    ]
